# Introduction to Python and Useful Data Science Libraries

There a couple of well established data science libraries that you will find useful when exploring security data.

Pandas library stands for Python Data Analysis Library. Pandas is a game changer when it comes to analysising data with Pytn and it is on eof the most preferred and widely used tools in data science.

Pandas takes data (CSV, TSV, SQL database) and creates a python objection with rows and columns called data frame what looks similar to tables in statistical software (Excel, SPSS, R). This makes it easier to work with in comparison to working with lists and/or dictionaries through for loops or list comprehension.

In order to use Pandas in your Jupyter Notebook you need to import the Pandas library first. Importing the library means loading it into the memory and then it's there for you to work with. In order to import Pandas all you have to do is the run the following code:

In [1]:
import pandas as pd

The second part `pd` allows you to access Pandas with `pd.command` instead of needing to write `pandas.command` every time you need to use it. I also imported numpy because it is very useful library for scientific computing with Python. Now Pandas is ready for use! You would need to do this everytime you start a new Jupyter Notebook.

### Loading and Saving Data with Pandas

When you want to use Pandas for data analysis, you'll usually use it in one of three different ways:
* Convert a Python's list, dictionary or Numpy array to a Pandas data frame
* Open a local file using Pandas, usally a CSV file, but could also be delimited text file (like TSV), Excel, etc
* Open a remote file or database like a CSV or a JSON on a website through a URL or read from a SQL table/database

Below we will demonstrate reading a local file (JSON file) into a Pandas data frame.

In [2]:
df = pd.read_json('data/ISP_abuse_email_feed.json')

#### ISP Abuse Email Feed

Feed showing indicators of compromise from various Abuse reports locaed here: http://www.webiron.com/abuse_feed/

In [3]:
print(df)

        attacker_ip                days_unresolved emails_deliverable  \
0           0.0.0.0                            NaN                Yes
1     178.137.19.79    <font color="red">20</font>                Yes
2    178.137.80.158    <font color="red">20</font>                Yes
3   178.137.167.214    <font color="red">20</font>                Yes
4   178.137.167.214    <font color="red">20</font>                Yes
5    178.137.80.158    <font color="red">20</font>                Yes
6    77.154.194.148     <font color="red">5</font>                Yes
7     45.227.253.98  <font color="green"><3</font>                Yes
8    46.229.168.142   <font color="red">109</font>                Yes
9    46.229.168.142   <font color="red">109</font>                Yes
10    93.144.60.145  <font color="green"><3</font>                Yes
11   132.148.26.213  <font color="green"><3</font>                Yes
12   132.148.26.213  <font color="green"><3</font>                Yes
13    192.243.53.51   <font color="red">104</font>                Yes
14  213.174.146.211   <font color="red">103</font>                Yes
15  213.174.146.212   <font color="red">104</font>                Yes
16  213.174.146.213   <font color="red">104</font>                Yes
17     68.35.154.20  <font color="green"><3</font>                Yes
18   159.65.145.165     <font color="red">5</font>                Yes
19   132.148.26.213  <font color="green"><3</font>                Yes
20   159.65.145.165     <font color="red">5</font>                Yes
21     51.38.48.186  <font color="green"><3</font>                Yes
22    192.243.53.51   <font color="red">104</font>                Yes
23  213.174.146.211   <font color="red">103</font>                Yes
24    82.118.226.36     <font color="red">7</font>                Yes
25  213.174.146.212   <font color="red">104</font>                Yes
26   37.115.187.223    <font color="red">15</font>                Yes
27  213.174.146.213   <font color="red">104</font>                Yes
28   188.166.91.236  <font color="green"><3</font>                Yes
29   188.166.91.236  <font color="green"><3</font>                Yes
30   198.108.66.240    <font color="red">85</font>                Yes
31     37.119.17.71     <font color="red">5</font>                Yes
32    45.227.253.98  <font color="green"><3</font>                Yes
33   178.137.80.158    <font color="red">20</font>                Yes
34   37.115.187.223    <font color="red">15</font>                Yes
35   37.115.187.192    <font color="red">20</font>                Yes
36   37.115.187.192    <font color="red">20</font>                Yes
37    178.137.19.79    <font color="red">20</font>                Yes
38  178.137.167.214    <font color="red">20</font>                Yes
39  178.137.167.214    <font color="red">20</font>                Yes
40   178.137.80.158    <font color="red">20</font>                Yes
41   178.137.17.250    <font color="red">15</font>                Yes
42    46.119.126.51    <font color="red">15</font>                Yes
43   37.115.184.170    <font color="red">15</font>                Yes
44    45.227.253.98  <font color="green"><3</font>                Yes
45    178.137.19.79    <font color="red">20</font>                Yes
46   61.228.115.175  <font color="green"><3</font>                Yes
47   91.211.142.242  <font color="green"><3</font>                Yes
48    104.148.64.26     <font color="red">5</font>                Yes
49     125.27.10.69    <font color="red">88</font>                Yes
50   198.108.66.240    <font color="red">85</font>                Yes

   entry_type                                       event_emails  \
0        None                                [sales@webiron.com]
1      opened                          [hostmaster@kyivstar.net]
2      opened                          [hostmaster@kyivstar.net]
3      opened                                 [noc@kyivstar.net]
4      opened                          [hostmaster@kyivstar.net]
5      opened                                 [noc@kyivstar.net]
6      report                 [abuse@gaoland.net, abuse@sfr.net]
7      report                                 [abuse@lacnic.net]
8    resolved                     [abuse@datawebglobalgroup.com]
9      report  [abuse@semrush.com, abuse@datawebglobalgroup.com]
10     opened                     [italy.abuse@mail.vodafone.it]
11     opened                           [abuse@secureserver.net]
12     opened                                [abuse@godaddy.com]
13   resolved                        [abuse@advancedhosters.com]
14   resolved                     [abuse@datawebglobalgroup.com]
15   resolved                     [abuse@datawebglobalgroup.com]
16   resolved                     [abuse@datawebglobalgroup.com]
17     report                                [abuse@comcast.net]
18     opened                           [abuse@digitalocean.com]
19     report        [abuse@secureserver.net, abuse@godaddy.com]
20     report                           [abuse@digitalocean.com]
21     report                                    [abuse@ovh.net]
22     report                        [abuse@advancedhosters.com]
23     report                     [abuse@datawebglobalgroup.com]
24     report                                [abuse@verdina.net]
25     report                     [abuse@datawebglobalgroup.com]
26     report  [hostmaster@kyivstar.net, abuse@kyivstar.net, ...
27     report                     [abuse@datawebglobalgroup.com]
28     opened                           [abuse@digitalocean.com]
29     report                           [abuse@digitalocean.com]
30     report            [phil.carolan@lisd.us, abuse@censys.io]
31     opened                     [italy.abuse@mail.vodafone.it]
32     report                                 [abuse@lacnic.net]
33     opened                          [hostmaster@kyivstar.net]
34     opened                               [abuse@kyivstar.net]
35     opened                                 [noc@kyivstar.net]
36     opened                          [hostmaster@kyivstar.net]
37     opened                                 [noc@kyivstar.net]
38     opened                                 [noc@kyivstar.net]
39     opened                          [hostmaster@kyivstar.net]
40     opened                                 [noc@kyivstar.net]
41     opened                               [abuse@kyivstar.net]
42     opened                               [abuse@kyivstar.net]
43     opened                               [abuse@kyivstar.net]
44     report                                 [abuse@lacnic.net]
45     opened                          [hostmaster@kyivstar.net]
46     report  [spam@ms1.hinet.net, abuse@hinet.net, network-...
47     report                                 [abuse@telplus.ru]
48     report                             [abuse@globalfrag.com]
49     report  [root@tot.co.th, postmaster@tot.co.th, abuse@i...
50     report            [phil.carolan@lisd.us, abuse@censys.io]

                                            event_msg  \
0                        List provided by Webiron.com
1                   Host has opened and viewed report
2                   Host has opened and viewed report
3                   Host has opened and viewed report
4                   Host has opened and viewed report
5                   Host has opened and viewed report
6   Shellshock Exploiter Bot (shell malware Downlo...
7                        Abusive network connectivity
8            Host has confirmed resolution of issues.
9                     SemrushBot Intelligence Crawler
10                  Host has opened and viewed report
11                  Host has opened and viewed report
12                  Host has opened and viewed report
13           Host has confirmed resolution of issues.
14           Host has confirmed resolution of issues.
15           Host has confirmed resolution of issues.
16           Host has confirmed resolution of issues.
17                  Unidentified Intelligence Crawler
18                  Host has opened and viewed report
19  DB GUI Exploit Scanner Bot,<br />Client softwa...
20  Shellshock Exploiter Bot (shell malware Downlo...
21                         Fake Referrer Log SPAM Bot
22       Exploiter Scanner Bot (Generic/Multi Target)
23       Exploiter Scanner Bot (Generic/Multi Target)
24                             Orphan Malware Scanner
25       Exploiter Scanner Bot (Generic/Multi Target)
26                         Fake Referrer Log SPAM Bot
27       Exploiter Scanner Bot (Generic/Multi Target)
28                  Host has opened and viewed report
29  Shellshock Exploiter Bot (shell malware Downlo...
30                                    Exploit Scanner
31                  Host has opened and viewed report
32                       Abusive network connectivity
33                  Host has opened and viewed report
34                  Host has opened and viewed report
35                  Host has opened and viewed report
36                  Host has opened and viewed report
37                  Host has opened and viewed report
38                  Host has opened and viewed report
39                  Host has opened and viewed report
40                  Host has opened and viewed report
41                  Host has opened and viewed report
42                  Host has opened and viewed report
43                  Host has opened and viewed report
44                       Abusive network connectivity
45                  Host has opened and viewed report
46                  Unidentified Intelligence Crawler
47                             Orphan Malware Scanner
48  Vulnerability Scan Bot,<br />Orphan Malware Sc...
49  DB GUI Exploit Scanner Bot,<br />Client softwa...
50                                    Exploit Scanner

                       event_time  incidents_reported
0        0000-00-00 00:00:00.0-07                   0
1   2019-04-15 18:08:16.927385-07                   0
2   2019-04-15 18:08:15.108328-07                   0
3   2019-04-15 18:08:14.009988-07                   0
4   2019-04-15 18:08:13.009396-07                   0
5   2019-04-15 18:08:09.676759-07                   0
6   2019-04-15 18:06:36.826063-07                   6
7    2019-04-15 18:05:16.72206-07                  51
8   2019-04-15 18:05:07.808498-07                   0
9   2019-04-15 18:04:47.982869-07                   1
10  2019-04-15 18:04:26.737292-07                   0
11  2019-04-15 18:01:10.226349-07                   0
12  2019-04-15 18:01:09.876332-07                   0
13  2019-04-15 18:01:02.330277-07                   0
14  2019-04-15 18:01:02.149666-07                   0
15  2019-04-15 18:00:59.500013-07                   0
16  2019-04-15 18:00:54.773947-07                   0
17   2019-04-15 18:00:50.80633-07                   1
18  2019-04-15 18:00:41.074027-07                   0
19  2019-04-15 18:00:39.672996-07                  70
20  2019-04-15 18:00:38.834403-07                   4
21  2019-04-15 18:00:36.866916-07                   1
22  2019-04-15 18:00:36.669861-07                   2
23  2019-04-15 18:00:36.157695-07                   1
24  2019-04-15 18:00:35.224131-07                   1
25  2019-04-15 18:00:34.786341-07                   2
26  2019-04-15 18:00:33.373609-07                   3
27  2019-04-15 18:00:32.990925-07                   2
28  2019-04-15 18:00:30.438845-07                   0
29   2019-04-15 18:00:27.91616-07                   5
30  2019-04-15 18:00:27.447742-07                   2
31  2019-04-15 18:00:05.782902-07                   0
32  2019-04-15 17:05:10.408747-07                  51
33  2019-04-15 16:07:47.149901-07                   0
34  2019-04-15 16:07:03.945803-07                   0
35  2019-04-15 16:06:44.402971-07                   0
36  2019-04-15 16:06:43.218438-07                   0
37   2019-04-15 16:06:40.32083-07                   0
38  2019-04-15 16:06:39.345807-07                   0
39  2019-04-15 16:06:26.217303-07                   0
40   2019-04-15 16:06:25.21394-07                   0
41   2019-04-15 16:06:19.51453-07                   0
42  2019-04-15 16:06:15.577857-07                   0
43  2019-04-15 16:06:13.209389-07                   0
44  2019-04-15 16:05:09.641455-07                  71
45  2019-04-15 16:03:12.672574-07                   0
46  2019-04-15 16:00:52.459012-07                   1
47  2019-04-15 16:00:41.792437-07                   1
48  2019-04-15 16:00:36.313361-07                   2
49  2019-04-15 16:00:34.480716-07                  71
50  2019-04-15 16:00:31.584055-07                   1

When the Dataframe is large, like above, you can still print it to the screen, or you can simply print the first 5 lines of the DataFrame with the `.head()` function.

In [4]:
df.head()

,attacker_ip,days_unresolved,emails_deliverable,entry_type,event_emails,event_msg,event_time,incidents_reported
0,0.0.0.0,NaN,Yes,None,[sales@webiron.com],List provided by Webiron.com,0000-00-00 00:00:00.0-07,0
1,178.137.19.79,"<font color=""red"">20</font>",Yes,opened,[hostmaster@kyivstar.net],Host has opened and viewed report,2019-04-15 18:08:16.927385-07,0
2,178.137.80.158,"<font color=""red"">20</font>",Yes,opened,[hostmaster@kyivstar.net],Host has opened and viewed report,2019-04-15 18:08:15.108328-07,0
3,178.137.167.214,"<font color=""red"">20</font>",Yes,opened,[noc@kyivstar.net],Host has opened and viewed report,2019-04-15 18:08:14.009988-07,0
4,178.137.167.214,"<font color=""red"">20</font>",Yes,opened,[hostmaster@kyivstar.net],Host has opened and viewed report,2019-04-15 18:08:13.009396-07,0

To view the last n entries, we can use the `.tail()` function.

In [5]:
df.tail(5)

,attacker_ip,days_unresolved,emails_deliverable,entry_type,event_emails,event_msg,event_time,incidents_reported
46,61.228.115.175,"<font color=""green""><3</font>",Yes,report,"[spam@ms1.hinet.net, abuse@hinet.net, network-...",Unidentified Intelligence Crawler,2019-04-15 16:00:52.459012-07,1
47,91.211.142.242,"<font color=""green""><3</font>",Yes,report,[abuse@telplus.ru],Orphan Malware Scanner,2019-04-15 16:00:41.792437-07,1
48,104.148.64.26,"<font color=""red"">5</font>",Yes,report,[abuse@globalfrag.com],"Vulnerability Scan Bot,<br />Orphan Malware Sc...",2019-04-15 16:00:36.313361-07,2
49,125.27.10.69,"<font color=""red"">88</font>",Yes,report,"[root@tot.co.th, postmaster@tot.co.th, abuse@i...","DB GUI Exploit Scanner Bot,<br />Client softwa...",2019-04-15 16:00:34.480716-07,71
50,198.108.66.240,"<font color=""red"">85</font>",Yes,report,"[phil.carolan@lisd.us, abuse@censys.io]",Exploit Scanner,2019-04-15 16:00:31.584055-07,1

By calling the `.info()` function, we can see information regarding the column names, total number of entries, and the types for each column.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
attacker_ip           51 non-null object
days_unresolved       50 non-null object
emails_deliverable    51 non-null object
entry_type            51 non-null object
event_emails          51 non-null object
event_msg             51 non-null object
event_time            51 non-null object
incidents_reported    51 non-null int64
dtypes: int64(1), object(7)
memory usage: 3.3+ KB

From this data, we can see we have 51 entries (rows) in our DataFrame. We can also see that days_unresolved appears to be missing an entry.

    The `.describe()` function can be incredibly useful when analyzing a dataset. By calling this function, Pandas will tell us the count, mean, standard devication, interquartile range, maximu, and minumum values for each column in our dataset which has a numerical type.

In [7]:
df.describe()

       incidents_reported
count           51.000000
mean             6.862745
std             18.918794
min              0.000000
25%              0.000000
50%              0.000000
75%              2.000000
max             71.000000

Pandas provides many tools to manipulate, filter, combine and transform your data. To grab the first 10 rows from the event_time column, we can enter the key and indicies in square brackets []. You can access a column by typing its name right after the DataFrame .

In [8]:
# Without indicies, we can grab the entire column
print(df['event_time'][0:10])
print('')
# This is equivalent
print(df.event_time[0:10])

0         0000-00-00 00:00:00.0-07
1    2019-04-15 18:08:16.927385-07
2    2019-04-15 18:08:15.108328-07
3    2019-04-15 18:08:14.009988-07
4    2019-04-15 18:08:13.009396-07
5    2019-04-15 18:08:09.676759-07
6    2019-04-15 18:06:36.826063-07
7     2019-04-15 18:05:16.72206-07
8    2019-04-15 18:05:07.808498-07
9    2019-04-15 18:04:47.982869-07
Name: event_time, dtype: object

0         0000-00-00 00:00:00.0-07
1    2019-04-15 18:08:16.927385-07
2    2019-04-15 18:08:15.108328-07
3    2019-04-15 18:08:14.009988-07
4    2019-04-15 18:08:13.009396-07
5    2019-04-15 18:08:09.676759-07
6    2019-04-15 18:06:36.826063-07
7     2019-04-15 18:05:16.72206-07
8    2019-04-15 18:05:07.808498-07
9    2019-04-15 18:04:47.982869-07
Name: event_time, dtype: object

If we look at the type of each column, we can see that DataFrames are actually mad eup of Pandas Series.

In [9]:
type(df.event_time)

pandas.core.series.Series

By grabbing an individual column as a series, we can calculate the mean, median or a number of statistical values by using methods  of the same name.

In [10]:
print('MEAN: ' + str(df.incidents_reported.mean()))
print('MEDIAN: ' + str(df.incidents_reported.median()))
print('MAX: ' + str(df.incidents_reported.max()))
print('MIN: ' + str(df.incidents_reported.min()))
print('SUM: ' + str(df.incidents_reported.sum()))

MEAN: 6.862745098039215
MEDIAN: 0.0
MAX: 71
MIN: 0
SUM: 350

We can also grab a number of columns at once by passing in a list of columns.

In [11]:
df[['attacker_ip', 'emails_deliverable', 'entry_type']]

        attacker_ip emails_deliverable entry_type
0           0.0.0.0                Yes       None
1     178.137.19.79                Yes     opened
2    178.137.80.158                Yes     opened
3   178.137.167.214                Yes     opened
4   178.137.167.214                Yes     opened
5    178.137.80.158                Yes     opened
6    77.154.194.148                Yes     report
7     45.227.253.98                Yes     report
8    46.229.168.142                Yes   resolved
9    46.229.168.142                Yes     report
10    93.144.60.145                Yes     opened
11   132.148.26.213                Yes     opened
12   132.148.26.213                Yes     opened
13    192.243.53.51                Yes   resolved
14  213.174.146.211                Yes   resolved
15  213.174.146.212                Yes   resolved
16  213.174.146.213                Yes   resolved
17     68.35.154.20                Yes     report
18   159.65.145.165                Yes     opened
19   132.148.26.213                Yes     report
20   159.65.145.165                Yes     report
21     51.38.48.186                Yes     report
22    192.243.53.51                Yes     report
23  213.174.146.211                Yes     report
24    82.118.226.36                Yes     report
25  213.174.146.212                Yes     report
26   37.115.187.223                Yes     report
27  213.174.146.213                Yes     report
28   188.166.91.236                Yes     opened
29   188.166.91.236                Yes     report
30   198.108.66.240                Yes     report
31     37.119.17.71                Yes     opened
32    45.227.253.98                Yes     report
33   178.137.80.158                Yes     opened
34   37.115.187.223                Yes     opened
35   37.115.187.192                Yes     opened
36   37.115.187.192                Yes     opened
37    178.137.19.79                Yes     opened
38  178.137.167.214                Yes     opened
39  178.137.167.214                Yes     opened
40   178.137.80.158                Yes     opened
41   178.137.17.250                Yes     opened
42    46.119.126.51                Yes     opened
43   37.115.184.170                Yes     opened
44    45.227.253.98                Yes     report
45    178.137.19.79                Yes     opened
46   61.228.115.175                Yes     report
47   91.211.142.242                Yes     report
48    104.148.64.26                Yes     report
49     125.27.10.69                Yes     report
50   198.108.66.240                Yes     report

## Exercise 1

We have already provided you with a dataset from the National Vulnerability Database. The file is located in `data/nvdcve.json`. You are taksed with the following:
* Create a dataframe
* List the first 10 entries of the dataframe
* Show the CVE_data_version of the first 5 people
* Calculate the mean of the number of CVEs
* Calculate the median of the number of CVEs

Reference: 
* https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673
* https://www.secrepo.com/
* https://github.com/ADSA-UIUC/intro-to-pandas-and-matplotlib/blob/master/intro-to-pandas-and-matplotlib-completed.ipynb
* https://nvd.nist.gov/vuln/data-feeds